let state={ran:false,caseKey:'spike',threshold:65,sources:12,period:14,docs:[],claims:[],progress:0,services:{'Control Center':true,'PostgreSQL':true,'Telegram bot':true,'Ingestion worker':true,'Evidence worker':true,'Report worker':true}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function switchMode(mode){$$('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$$('.mode-section').forEach(x=>x.classList.remove('active'));$('#'+mode+'Mode').classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(mode==='report')buildReport()}
window.switchMode=switchMode;$('#modebar').onclick=e=>{if(e.target.dataset.mode)switchMode(e.target.dataset.mode)};
function lineChart(el,raw,ind){const w=760,h=240,p=34,max=Math.max(...raw,...ind)*1.15;let x=i=>p+i*(w-2*p)/(raw.length-1),y=v=>h-p-v*(h-2*p)/max;let grid='';for(let i=0;i<5;i++){let yy=p+i*(h-2*p)/4;grid+=`<line class="gridline" x1="${p}" y1="${yy}" x2="${w-p}" y2="${yy}"/>`}let path=a=>a.map((v,i)=>(i?'L':'M')+x(i)+','+y(v)).join(' ');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}">${grid}<line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><path d="${path(raw)}" fill="none" stroke="#6fa8ff" stroke-width="4"/><path d="${path(ind)}" fill="none" stroke="#55d6be" stroke-width="4"/>${raw.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#6fa8ff"/>`).join('')}${ind.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#55d6be"/>`).join('')}</svg>`}
function barChart(el,data){const w=700,h=250,p=34,max=Math.max(...data.map(x=>x[1]))*1.12,bw=(w-2*p)/data.length*.62;el.innerHTML=`<svg viewBox="0 0 ${w} ${h}"><line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/>${data.map((d,i)=>{let x=p+i*(w-2*p)/data.length+12,y=h-p-d[1]*(h-2*p)/max,hh=h-p-y;return `<rect x="${x}" y="${y}" width="${bw}" height="${hh}" rx="7" fill="#b08cff"/><text x="${x+bw/2}" y="${h-12}" text-anchor="middle" fill="#9fb0c5" font-size="11">${d[0].slice(0,13)}</text><text x="${x+bw/2}" y="${y-7}" text-anchor="middle" fill="#edf5ff" font-size="12">${d[1]}%</text>`}).join('')}</svg>`}
function spreadChart(el){const nodes=[['Источник',95,120,'#55d6be'],['Канал A',250,55,'#6fa8ff'],['Канал B',250,125,'#6fa8ff'],['Канал C',250,195,'#6fa8ff'],['Канал D',430,75,'#ffbd59'],['Канал E',430,155,'#ffbd59'],['Web',590,120,'#b08cff']];const edges=[[0,1],[0,2],[0,3],[1,4],[2,4],[2,5],[3,5],[4,6],[5,6]];el.innerHTML=`<svg viewBox="0 0 690 250">${edges.map(e=>`<line x1="${nodes[e[0]][1]}" y1="${nodes[e[0]][2]}" x2="${nodes[e[1]][1]}" y2="${nodes[e[1]][2]}" stroke="#39506c" stroke-width="2"/>`).join('')}${nodes.map(n=>`<g><circle cx="${n[1]}" cy="${n[2]}" r="28" fill="${n[3]}" opacity=".9"/><text x="${n[1]}" y="${n[2]+4}" text-anchor="middle" font-size="10" fill="#06101c" font-weight="800">${n[0]}</text></g>`).join('')}</svg>`}
function generateDocs(){const mult=state.sources/12;state.docs=[];for(let i=0;i<Math.max(8,Math.round(12*mult));i++){let b=docsBase[i%docsBase.length];state.docs.push({...b,id:'D-'+String(i+1).padStart(3,'0'),views:Math.round(b.views*(.75+Math.random()*.6)),time:String(8+Math.floor(i/3)).padStart(2,'0')+':'+String((i*13)%60).padStart(2,'0')})}}
function renderDocs(filter='all'){let arr=state.docs.filter(d=>filter==='all'||(filter==='unique'&&d.unique)||(filter==='duplicate'&&!d.unique)||(filter==='high'&&d.risk==='high'));$('#docFeed').innerHTML=arr.length?arr.map(d=>`<div class="doc" data-doc="${d.id}"><div class="top"><b>${d.channel}</b><span class="pill ${d.risk==='high'?'high':d.risk==='med'?'med':'low'}">${d.risk}</span></div><h4>${d.title}</h4><div class="meta">${d.time} · ${d.views?d.views.toLocaleString('ru-RU')+' просмотров':'официальный документ'} · cluster ${d.cluster} · ${d.unique?'уникальный':'перепечатка'}</div><div class="tags">${d.topics.map(t=>`<span class="chip">${t}</span>`).join('')}</div></div>`).join(''):'<div class="empty">Нет документов по фильтру.</div>';$$('[data-doc]').forEach(x=>x.onclick=()=>openDoc(x.dataset.doc))}
function openDoc(id){let d=state.docs.find(x=>x.id===id);if(!d)return;$('#drawerContent').innerHTML=`<div class="ey">Документ ${d.id}</div><h2>${d.title}</h2><p>${d.text}</p><div class="card" style="box-shadow:none"><b>Источник</b><p>${d.channel}</p><b>Статус</b><p>${d.unique?'Независимый документ':'Перепечатка / вторичное распространение'}</p><b>Кластер</b><p>${d.cluster}</p><b>Content hash</b><p class="small">${d.hash}</p><b>Сущности</b><p>${d.entities.join(', ')}</p><b>Темы</b><p>${d.topics.join(', ')}</p></div>`;$('#drawer').classList.add('open')}
$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('open');$('#drawer').onclick=e=>{if(e.target.id==='drawer')$('#drawer').classList.remove('open')};
function renderClaims(){const c=CASES[state.caseKey];$('#executiveClaims').innerHTML=c.claims.map(x=>`<div class="claim"><div><span class="pill ${x.sev==='high'?'high':x.sev==='med'?'med':'low'}">${x.sev.toUpperCase()}</span> <span class="pill info">${x.conf}% confidence</span></div><h3>${x.title}</h3><p class="muted">${x.action}</p><button class="btn alt" onclick="openClaim('${x.id}')">Доказательства</button></div>`).join('');$('#claimsPanel').innerHTML=c.claims.map(x=>`<div class="claim" style="margin-bottom:10px"><div class="section-title"><div><span class="pill ${x.sev==='high'?'high':x.sev==='med'?'med':'low'}">${x.sev.toUpperCase()}</span> <span class="pill ${x.status==='verified'?'ok':'med'}">${x.status}</span></div><span class="small muted">${x.id}</span></div><h3>${x.title}</h3><div class="claim-grid"><div><b>Confidence</b><div class="progress"><i style="width:${x.conf}%"></i></div><span class="small muted">${x.conf}%</span></div><div><b>Source independence</b><div class="progress"><i style="width:${x.ind}%"></i></div><span class="small muted">${x.ind}%</span></div></div><div class="evidence"><b>${x.evidence} доказательства</b><br>${x.caveat}</div><p><b>Рекомендуемое действие:</b> ${x.action}</p><div class="actions"><button class="btn alt verify" data-id="${x.id}" data-status="verified">Подтвердить</button><button class="btn alt verify" data-id="${x.id}" data-status="partial">Частично</button><button class="btn alt verify" data-id="${x.id}" data-status="rejected">Отклонить</button><button class="btn warn acquire" data-id="${x.id}">Найти доказательства</button></div></div>`).join('');$$('.verify').forEach(b=>b.onclick=()=>{let x=c.claims.find(z=>z.id===b.dataset.id);x.status=b.dataset.status;toast('Решение аналитика сохранено');renderClaims();renderAudit()});$$('.acquire').forEach(b=>b.onclick=()=>{let x=c.claims.find(z=>z.id===b.dataset.id);x.evidence++;x.conf=Math.min(99,x.conf+4);x.ind=Math.min(96,x.ind+6);toast('Найдено новое независимое подтверждение');renderClaims();renderMatrix();renderAudit()})}
window.openClaim=id=>{let x=CASES[state.caseKey].claims.find(z=>z.id===id);$('#drawerContent').innerHTML=`<div class="ey">Claim ${x.id}</div><h2>${x.title}</h2><div class="card" style="box-shadow:none"><p><b>Severity:</b> ${x.sev}</p><p><b>Confidence:</b> ${x.conf}%</p><p><b>Independence:</b> ${x.ind}%</p><p><b>Ограничение:</b> ${x.caveat}</p><p><b>Действие:</b> ${x.action}</p></div><h3>Evidence bundle</h3>${state.docs.slice(0,x.evidence).map(d=>`<div class="evidence"><b>${d.id} · ${d.channel}</b><br>${d.title}<br><span class="small muted">cluster ${d.cluster} · ${d.unique?'independent':'copy'}</span></div>`).join('')}`;$('#drawer').classList.add('open')}
function renderMatrix(){const rows=state.docs.slice(0,10);$('#matrixBody').innerHTML=rows.map(d=>`<tr><td>${d.id}</td><td>${d.channel}</td><td>${d.cluster}</td><td>${d.unique?'Primary / independent':'Amplifier / copy'}</td><td><span class="pill ${d.unique?'ok':'med'}">${d.unique?'Да':'Нет'}</span></td></tr>`).join('')}
function renderTimeline(){const t=CASES[state.caseKey].timeline;$('#claimTimeline').innerHTML=t.map((x,i)=>`<div class="node"><div class="muted">${x[0]}</div><h3>${x[1]}</h3><span class="pill ${x[2]==='verified'?'ok':x[2]==='updates'?'info':'violet'}">${x[2]}</span><p class="small muted">Версия ${i+1}. Открыть доказательства и причину изменения.</p></div>`).join('')}
function renderExecutive(){const c=CASES[state.caseKey];$('#kRaw').textContent=c.raw;$('#kUnique').textContent=c.unique;$('#kSignal').textContent=c.signal+'%';$('#kClaims').textContent=c.critical;$('#decisionBox').innerHTML=`<span class="pill high">Решение требуется</span><h3>${c.name}</h3><p>${c.decision}</p><button class="btn" onclick="switchMode('report')">Сформировать отчёт</button>`;let raw=[18,24,27,41,62,78,75,69,88,93,81,73,66,58],ind=[12,15,16,20,25,31,30,29,34,36,32,28,27,24];if(state.caseKey==='supply'){raw=raw.map(x=>Math.round(x*.82));ind=ind.map(x=>Math.round(x*1.15))}if(state.caseKey==='narrative'){raw=raw.map(x=>Math.round(x*1.18));ind=ind.map(x=>Math.round(x*1.05))}lineChart($('#activityChart'),raw,ind);barChart($('#topicChart'),c.topics);spreadChart($('#spreadChart'));renderClaims()}
function renderServices(){$('#serviceList').innerHTML=Object.entries(state.services).map(([n,on])=>`<div class="service"><div><span class="dot ${on?'':'off'}"></span><b>${n}</b><div class="small muted">${on?'running · heartbeat 12s':'stopped'}</div></div><button class="btn alt svc" data-name="${n}">${on?'Restart':'Start'}</button></div>`).join('');$$('.svc').forEach(b=>b.onclick=()=>{state.services[b.dataset.name]=!state.services[b.dataset.name];toast('Статус сервиса изменён');renderServices();renderAudit()})}
function renderOperator(){$('#rulesList').innerHTML=`<div class="service"><div><b>Рост независимого сигнала</b><div class="small muted">Порог ${state.threshold}%</div></div><span class="pill ok">active</span></div><div class="service"><div><b>Новая сущность высокого риска</b><div class="small muted">Уведомление в Telegram</div></div><span class="pill ok">active</span></div><div class="service"><div><b>Противоречие verified claim</b><div class="small muted">Немедленная тревога</div></div><span class="pill ok">active</span></div>`;$('#queueList').innerHTML=['ingestion','normalization','analysis','evidence','report'].map((x,i)=>`<div class="service"><div><b>${x}</b><div class="small muted">${state.ran?(i<4?'completed':'ready'):'waiting'}</div></div><span class="pill ${state.ran?'ok':'info'}">${state.ran?'ok':'queued'}</span></div>`).join('');renderServices()}
function renderAudit(){const c=CASES[state.caseKey];const lines=[`[${new Date().toLocaleTimeString('ru-RU')}] workspace.selected ${c.name}`,`[hash] snapshot.baseline sha256: 74de…91aa`,`[hash] snapshot.current sha256: 912f…3bc1`,`[analysis] ${c.claims.length} claims generated`,`[evidence] independence recalculated`,`[audit] analyst decisions persisted`,`[ready] status=READY`];$('#auditLog').innerHTML=lines.map(x=>`<div>${x}</div>`).join('');$('#operatorLog').innerHTML=state.ran?lines.slice(0,5).map(x=>`<div>${x}</div>`).join(''):'<div>[waiting] Нажмите «Проверить и запустить».</div>'}
function renderSelfTest(){const tests=[['Configuration store','pass'],['PostgreSQL connection','pass'],['Migration head','pass'],['Demo dataset integrity','pass'],['Telegram API','simulated'],['Workers heartbeat','pass']];$('#selfTest').innerHTML=tests.map(t=>`<div class="service"><b>${t[0]}</b><span class="pill ${t[1]==='pass'?'ok':'info'}">${t[1]}</span></div>`).join('')}
function renderAll(){renderExecutive();renderDocs();renderMatrix();renderTimeline();renderOperator();renderAudit();renderSelfTest();buildReport()}
function runSimulation(){state.caseKey=$('#caseSelect').value;state.period=+$('#periodSelect').value;state.threshold=+$('#thresholdSelect').value;state.sources=+$('#sourceSelect').value;state.progress=0;state.ran=false;generateDocs();$('#simState').textContent='Сбор данных';$('#simState').className='pill info';const steps=['Проверка источников','Сбор сообщений','Нормализация и дедупликация','Распознавание тем и сущностей','Формирование claims','Построение evidence','Подготовка отчёта'];let i=0;const timer=setInterval(()=>{state.progress=Math.round((i+1)/steps.length*100);$('#simProgress').style.width=state.progress+'%';$('#simText').textContent=steps[i]+'…';i++;if(i>=steps.length){clearInterval(timer);state.ran=true;$('#simState').textContent='READY';$('#simState').className='pill ok';$('#simText').textContent='Анализ завершён. Дашборд, evidence и отчёт обновлены.';renderAll();toast('Анализ завершён')}} ,420)}
$('#runBtn').onclick=runSimulation;$('#resetBtn').onclick=()=>{state.ran=false;state.docs=[];$('#simProgress').style.width='0%';$('#simText').textContent='Ожидается запуск.';$('#simState').textContent='Готов к запуску';['kRaw','kUnique','kClaims'].forEach(id=>$('#'+id).textContent='0');$('#kSignal').textContent='0%';$('#activityChart').innerHTML='';$('#topicChart').innerHTML='';$('#spreadChart').innerHTML='';$('#decisionBox').innerHTML='<div class="empty">Запустите анализ.</div>';$('#executiveClaims').innerHTML='';$('#docFeed').innerHTML='';$('#claimsPanel').innerHTML='<div class="empty">Запустите анализ.</div>';toast('Эмулятор сброшен')};
$('#tourBtn').onclick=()=>{runSimulation();setTimeout(()=>switchMode('executive'),3200);setTimeout(()=>switchMode('analyst'),6500);setTimeout(()=>switchMode('operator'),9800);setTimeout(()=>switchMode('technical'),12800);setTimeout(()=>switchMode('report'),15800)};
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDocs(b.dataset.filter)});
$('#operatorStart').onclick=()=>{state.ran=true;generateDocs();renderAll();toast('Workspace проверен и запущен')};$('#addSource').onclick=()=>toast('Источник добавлен в demo-конфигурацию');
$$('.tgcmd').forEach(b=>b.onclick=()=>{const cmd=b.textContent;const c=CASES[state.caseKey];const replies={'/summary':`За ${state.period} дней: ${c.raw} сообщений, ${c.unique} уникальных документов. Независимый сигнал ${c.signal}%. Главный вывод: ${c.claims[0].title}`,'/risks':c.claims.filter(x=>x.sev==='high').map(x=>'⚠️ '+x.title).join('\n'),'/compare':`Baseline vs current: объём публикаций вырос, но после дедупликации изменение составляет ${c.signal}%.`,'/evidence':`Claims: ${c.claims.length}. Evidence refs: ${c.claims.reduce((a,x)=>a+x.evidence,0)}. Primary clusters: ${new Set(state.docs.filter(x=>x.unique).map(x=>x.cluster)).size}.`,'/report':'Отчёт готов. Откройте вкладку «Отчёт» для PDF / JSON / CSV.'};$('#chatBox').insertAdjacentHTML('beforeend',`<div class="msg user">${cmd}</div><div class="msg bot">${(replies[cmd]||'Команда выполнена').replaceAll('\n','<br>')}</div>`);$('#chatBox').scrollTop=$('#chatBox').scrollHeight});
$('#triggerAlert').onclick=()=>{$('#chatBox').insertAdjacentHTML('beforeend','<div class="msg bot">🚨 Тревога: обнаружено противоречие ранее подтверждённому выводу. Confidence пересчитан. Откройте /evidence.</div>');toast('Telegram-уведомление отправлено')};
$('#runSelfTest').onclick=()=>{renderSelfTest();toast('Self-test: все обязательные проверки пройдены')};
function reportData(){const c=CASES[state.caseKey];return {generated_at:new Date().toISOString(),workspace:'Рынок БПЛА и комплектующих',case:c.name,period_days:state.period,sources:state.sources,summary:{raw:c.raw,unique:c.unique,independent_signal_percent:c.signal,decision:c.decision},claims:c.claims,documents:state.docs}}
function buildReport(){const c=CASES[state.caseKey],parts=$$('.reportPart:checked').map(x=>x.value);let html=`<div class="ey">Channel Analyzer Bot</div><h2>${$('#reportTitle')?.value||'Аналитическая записка'}</h2><p class="muted">${c.name} · период ${state.period} дней · ${state.sources} источников</p>`;if(parts.includes('summary'))html+=`<div class="rbox"><h3>Резюме для руководителя</h3><p>${c.decision}</p><p><b>${c.raw}</b> сообщений · <b>${c.unique}</b> уникальных документов · независимый сигнал <b>${c.signal}%</b></p></div>`;if(parts.includes('charts'))html+=`<div class="rbox"><h3>Ключевые показатели</h3><p>Рост общего потока сопоставляется с динамикой независимых источников. Доля перепечаток не используется как самостоятельное подтверждение.</p><ul>${c.topics.map(x=>`<li>${x[0]} — ${x[1]}%</li>`).join('')}</ul></div>`;if(parts.includes('claims'))html+=`<div class="rbox"><h3>Выводы и доказательства</h3>${c.claims.map(x=>`<p><b>${x.id}: ${x.title}</b><br>Confidence ${x.conf}%, independence ${x.ind}%. ${x.action}</p>`).join('')}</div>`;if(parts.includes('timeline'))html+=`<div class="rbox"><h3>Изменение утверждения</h3>${c.timeline.map(x=>`<p>${x[0]} — ${x[1]} <b>${x[2]}</b></p>`).join('')}</div>`;if(parts.includes('appendix'))html+=`<div class="rbox"><h3>Приложение: документы</h3>${state.docs.slice(0,8).map(d=>`<p><b>${d.id} · ${d.channel}</b><br>${d.title}<br><span class="muted">cluster ${d.cluster}, ${d.unique?'independent':'duplicate'}</span></p>`).join('')}</div>`;$('#reportPreview').innerHTML=html}
$('#buildReport').onclick=buildReport;$$('.reportPart').forEach(x=>x.onchange=buildReport);$('#reportTitle').oninput=buildReport;
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#downloadJson').onclick=()=>download('channel-analyzer-report.json','application/json',JSON.stringify(reportData(),null,2));$('#downloadCsv').onclick=()=>{let rows=['id,source,title,cluster,independent'];state.docs.forEach(d=>rows.push([d.id,d.channel,'"'+d.title.replaceAll('"','""')+'"',d.cluster,d.unique].join(',')));download('channel-analyzer-documents.csv','text/csv;charset=utf-8','\ufeff'+rows.join('\n'))};$('#downloadHtml').onclick=()=>download('channel-analyzer-report.html','text/html;charset=utf-8','<!doctype html><meta charset="utf-8"><title>Report</title><body>'+$('#reportPreview').innerHTML+'</body>');
renderServices();renderSelfTest();renderOperator();renderAudit();